apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: delayed
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
        autoscaling.knative.dev/target-burst-capacity: "-1" #keep activator on path
    spec:
      containerConcurrency: 1 # each pod handles only 1 request
      containers:
      - image: ko://github.com/psschwei/delayed
        env:
        - name: STARTUP
          value: "0"
        - name: REQUEST
          value: "30"
